export const KAFKA_TOPIC = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',

  USER_PROFILE_CREATED: 'USER_PROFILE_CREATED',
  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',

  FILE_CREATED: 'FILE_CREATED',
  FILE_UPDATED: 'FILE_UPDATED',

  POST_CREATED: 'POST_CREATED',
  POST_UPDATED: 'POST_UPDATED',

  COMMENT_CREATED: 'COMMENT_CREATED',
  COMMENT_UPDATED: 'COMMENT_UPDATED',

  FRIEND_REQUEST_CREATED: 'FRIEND_REQUEST_CREATED',
  FRIEND_REQUEST_UPDATED: 'FRIEND_REQUEST_UPDATED',
  FRIEND_REQUEST_DELETED: 'FRIEND_REQUEST_DELETED',
};
