export const BASE_STATUS_CODE = 1000;

const AuthStatusCode = {
  INVALID_PASSWORD: BASE_STATUS_CODE + 1,
  INVALID_EMAIL: BASE_STATUS_CODE + 2,
  USER_NOT_FOUND: BASE_STATUS_CODE + 3,
  USER_VERIFIED: BASE_STATUS_CODE + 4,
  TOO_MANY_VERIFICATION_REQUEST: BASE_STATUS_CODE + 5,
  USER_NOT_VERIFIED: BASE_STATUS_CODE + 6,
  USER_EXISTED: BASE_STATUS_CODE + 7,
  USER_TOKEN_NOT_FOUND: BASE_STATUS_CODE + 8,
  INVALID_USER_TOKEN: BASE_STATUS_CODE + 9,
} as const;

Object.keys(AuthStatusCode).forEach((item) => {
  AuthStatusCode[item] += BASE_STATUS_CODE;
});

export { AuthStatusCode };
